<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'title' => 'LKS Matematika SMP Kelas 8',
                'slug' => 'lks-matematika-smp-kelas-8',
                'description' => 'Buku LKS Matematika SMP untuk pembelajaran komprehensif dengan latihan dan pembahasan terstruktur.',
                'price' => 42000,
                'stock' => 35,
                'grade' => 'SMP 8',
                'subject' => 'Matematika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-MAT-08',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Matematika+SMP+8',
            ],
            [
                'title' => 'LKS Bahasa Indonesia SMA Kelas 10',
                'slug' => 'lks-bahasa-indonesia-sma-kelas-10',
                'description' => 'Latihan Bahasa Indonesia SMA kelas 10 yang cocok untuk persiapan ujian dan pembelajaran harian.',
                'price' => 38500,
                'stock' => 28,
                'grade' => 'SMA 10',
                'subject' => 'Bahasa Indonesia',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-BIN-10',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Indonesia+SMA+10',
            ],
            [
                'title' => 'LKS Fisika SMA Kelas 11',
                'slug' => 'lks-fisika-sma-kelas-11',
                'description' => 'Buku LKS Fisika SMA kelas 11 dengan soal uji konsep dan simulasi pembelajaran yang praktis.',
                'price' => 45000,
                'stock' => 30,
                'grade' => 'SMA 11',
                'subject' => 'Fisika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-FIS-11',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Fisika+SMA+11',
            ],
            [
                'title' => 'LKS IPA SD Kelas 6',
                'slug' => 'lks-ipa-sd-kelas-6',
                'description' => 'LKS IPA SD kelas 6 dengan latihan dasar dan penguatan konsep sains untuk siswa sekolah dasar.',
                'price' => 32000,
                'stock' => 40,
                'grade' => 'SD 6',
                'subject' => 'IPA',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-IPA-06',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+IPA+SD+6',
            ],
            [
                'title' => 'LKS Kimia SMA Kelas 12',
                'slug' => 'lks-kimia-sma-kelas-12',
                'description' => 'LKS Kimia SMA kelas 12 dengan soal-soal lengkap dan pembahasan untuk ujian akhir tahun.',
                'price' => 47000,
                'stock' => 24,
                'grade' => 'SMA 12',
                'subject' => 'Kimia',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-KIM-12',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Kimia+SMA+12',
            ],
            [
                'title' => 'LKS Bahasa Inggris SMP Kelas 9',
                'slug' => 'lks-bahasa-inggris-smp-kelas-9',
                'description' => 'LKS Bahasa Inggris SMP kelas 9 yang berisi latihan grammar, conversation, dan reading comprehension.',
                'price' => 39500,
                'stock' => 32,
                'grade' => 'SMP 9',
                'subject' => 'Bahasa Inggris',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-BIN-09',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Inggris+SMP+9',
            ],
            [
                'title' => 'LKS Sejarah SMA Kelas 11',
                'slug' => 'lks-sejarah-sma-kelas-11',
                'description' => 'LKS Sejarah SMA kelas 11 dengan rangkuman ringkas dan soal latihan untuk ujian semester.',
                'price' => 41000,
                'stock' => 26,
                'grade' => 'SMA 11',
                'subject' => 'Sejarah',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-SEJ-11',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Sejarah+SMA+11',
            ],
            [
                'title' => 'LKS Matematika SD Kelas 5',
                'slug' => 'lks-matematika-sd-kelas-5',
                'description' => 'LKS Matematika SD kelas 5 untuk membantu anak-anak menguasai konsep operasi dan geometri dasar.',
                'price' => 31000,
                'stock' => 38,
                'grade' => 'SD 5',
                'subject' => 'Matematika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-MAT-05',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Matematika+SD+5',
            ],
            [
                'title' => 'LKS Ekonomi SMA Kelas 12',
                'slug' => 'lks-ekonomi-sma-kelas-12',
                'description' => 'LKS Ekonomi SMA kelas 12 yang membantu siswa memahami teori dan soal ekonomi makro dan mikro.',
                'price' => 46000,
                'stock' => 20,
                'grade' => 'SMA 12',
                'subject' => 'Ekonomi',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-EKO-12',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Ekonomi+SMA+12',
            ],
            [
                'title' => 'LKS Geografi SMA Kelas 10',
                'slug' => 'lks-geografi-sma-kelas-10',
                'description' => 'LKS Geografi SMA kelas 10 untuk meningkatkan pemahaman tentang lingkungan dan dinamika bumi.',
                'price' => 40000,
                'stock' => 22,
                'grade' => 'SMA 10',
                'subject' => 'Geografi',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-GEO-10',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Geografi+SMA+10',
            ],
            [
                'title' => 'LKS Biologi SMP Kelas 7',
                'slug' => 'lks-biologi-smp-kelas-7',
                'description' => 'LKS Biologi SMP kelas 7 dengan latihan tentang sel, organisme, dan ekosistem.',
                'price' => 33000,
                'stock' => 36,
                'grade' => 'SMP 7',
                'subject' => 'Biologi',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-BIO-07',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Biologi+SMP+7',
            ],
            [
                'title' => 'LKS Bahasa Sunda SD Kelas 4',
                'slug' => 'lks-bahasa-sunda-sd-kelas-4',
                'description' => 'LKS Bahasa Sunda untuk SD kelas 4 dengan kosa kata dan latihan membaca yang mudah dipahami.',
                'price' => 29000,
                'stock' => 42,
                'grade' => 'SD 4',
                'subject' => 'Bahasa Sunda',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-SUN-04',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Sunda+SD+4',
            ],
            [
                'title' => 'LKS Matematika SMA Kelas 10',
                'slug' => 'lks-matematika-sma-kelas-10',
                'description' => 'LKS Matematika SMA kelas 10 lengkap dengan latihan fungsi, trigonometri, dan aljabar.',
                'price' => 44000,
                'stock' => 27,
                'grade' => 'SMA 10',
                'subject' => 'Matematika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-MAT-10',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Matematika+SMA+10',
            ],
            [
                'title' => 'LKS Bahasa Indonesia SMP Kelas 7',
                'slug' => 'lks-bahasa-indonesia-smp-kelas-7',
                'description' => 'LKS Bahasa Indonesia SMP kelas 7 dengan teks cerita, puisi, dan latihan soal kelas.',
                'price' => 36000,
                'stock' => 34,
                'grade' => 'SMP 7',
                'subject' => 'Bahasa Indonesia',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-BIN-07',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Indonesia+SMP+7',
            ],
            [
                'title' => 'LKS Fisika SMA Kelas 12',
                'slug' => 'lks-fisika-sma-kelas-12',
                'description' => 'LKS Fisika SMA kelas 12 berisi soal dan pembahasan untuk persiapan ujian nasional.',
                'price' => 48000,
                'stock' => 25,
                'grade' => 'SMA 12',
                'subject' => 'Fisika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-FIS-12',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Fisika+SMA+12',
            ],
            [
                'title' => 'LKS Seni Budaya SMP Kelas 8',
                'slug' => 'lks-seni-budaya-smp-kelas-8',
                'description' => 'LKS Seni Budaya SMP kelas 8 dengan pembahasan kreativitas seni dan budaya lokal.',
                'price' => 34000,
                'stock' => 29,
                'grade' => 'SMP 8',
                'subject' => 'Seni Budaya',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-SBN-08',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Seni+Budaya+SMP+8',
            ],
            [
                'title' => 'LKS PJOK SD Kelas 3',
                'slug' => 'lks-pjok-sd-kelas-3',
                'description' => 'LKS PJOK SD kelas 3 fokus pada gerak dasar, kesehatan, dan olahraga sederhana.',
                'price' => 28500,
                'stock' => 44,
                'grade' => 'SD 3',
                'subject' => 'PJOK',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-PJOK-03',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+PJOK+SD+3',
            ],
            [
                'title' => 'LKS Bahasa Arab SMA Kelas 11',
                'slug' => 'lks-bahasa-arab-sma-kelas-11',
                'description' => 'LKS Bahasa Arab SMA kelas 11 untuk memperkuat kosakata, tata bahasa, dan terjemahan.',
                'price' => 45000,
                'stock' => 21,
                'grade' => 'SMA 11',
                'subject' => 'Bahasa Arab',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-ARB-11',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Arab+SMA+11',
            ],
            [
                'title' => 'LKS TKP SKI Prakarya SMA Kelas 10',
                'slug' => 'lks-prakarya-sma-kelas-10',
                'description' => 'LKS Prakarya SMA kelas 10 dengan proyek kerajinan tangan, teknologi, dan kewirausahaan.',
                'price' => 43000,
                'stock' => 31,
                'grade' => 'SMA 10',
                'subject' => 'Prakarya',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-PRK-10',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Prakarya+SMA+10',
            ],
            [
                'title' => 'LKS Matematika SMP Kelas 7',
                'slug' => 'lks-matematika-smp-kelas-7',
                'description' => 'LKS Matematika SMP kelas 7 untuk memperkuat dasar bilangan, pecahan, dan geometri sederhana.',
                'price' => 38000,
                'stock' => 33,
                'grade' => 'SMP 7',
                'subject' => 'Matematika',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-MAT-07',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Matematika+SMP+7',
            ],
            [
                'title' => 'LKS Bahasa Jawa SD Kelas 2',
                'slug' => 'lks-bahasa-jawa-sd-kelas-2',
                'description' => 'LKS Bahasa Jawa SD kelas 2 dengan pembelajaran aksara, kosakata, dan ungkapan sehari-hari.',
                'price' => 27500,
                'stock' => 45,
                'grade' => 'SD 2',
                'subject' => 'Bahasa Jawa',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-JW-02',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+Bahasa+Jawa+SD+2',
            ],
            [
                'title' => 'LKS Pendidikan Agama Islam SMA Kelas 11',
                'slug' => 'lks-pai-sma-kelas-11',
                'description' => 'LKS PAI SMA kelas 11 untuk pembelajaran fiqh, akidah, dan akhlak secara struktur.',
                'price' => 43500,
                'stock' => 29,
                'grade' => 'SMA 11',
                'subject' => 'PAI',
                'publisher' => 'PT ABC Publisher',
                'sku' => 'ABC-LKS-PAI-11',
                'image' => 'https://via.placeholder.com/520x320.png?text=LKS+PAI+SMA+11',
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
